apiVersion: v2
name: ehrbase
version: 0.7.0
kubeVersion: ">=1.26"
description: EHRbase is an open source software backend for clinical application systems and electronic health records.
type: application
keywords:
  - ehrbase
  - openehr
  - ehr
home: https://github.com/konateq/ehrbase-helm-chart
sources:
  - https://github.com/konateq/ehrbase-helm-chart/tree/main/charts/ehrbase
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.x.x
  - condition: redis.enabled
    name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 20.x.x
maintainers:
  - name: Konateq
    url: https://konateq.com
# renovate: image=ehrbase/ehrbase
appVersion: "2.9.0"
