{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ehrbase.fullname" . }}-auth-secret
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | default (randAlphaNum 30) | b64enc }}
  admin-username: {{ .Values.auth.adminUsername | b64enc }}
  admin-password: {{ .Values.auth.adminPassword | default (randAlphaNum 30) | b64enc }}
{{- end }}