apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ehrbase.fullname" . }}-env-vars
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
data:
  DB_URL: {{ include "ehrbase.databaseUrl" . | quote }}
  DB_USER: {{ include "ehrbase.databaseUser" . | quote }}
  DB_USER_ADMIN: {{ include "ehrbase.databaseUser" . | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_ACCESS: "PUBLIC"
  MANAGEMENT_SERVER_PORT: {{ .Values.service.managementPort | quote }}