apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ehrbase.fullname" . }}-env-vars
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
data:
  DB_URL: {{ include "ehrbase.databaseUrl" . | quote }}
  DB_USER: {{ include "ehrbase.databaseUser" . | quote }}
  DB_USER_ADMIN: {{ include "ehrbase.databaseUser" . | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_ACCESS: "PUBLIC"
  MANAGEMENT_SERVER_PORT: {{ .Values.service.managementPort | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
  {{- if .Values.auth.enabled }}
  SECURITY_AUTHTYPE: "BASIC"
  {{- end }}
  {{- if .Values.tls.enabled }}
  SERVER_SSL_ENABLED: "true"
  SERVER_SSL_CERTIFICATE: "/app/certs/tls.crt"
  SERVER_SSL_CERTIFICATEPRIVATEKEY: "/app/certs/tls.key"
  {{- end }}
  {{- if or .Values.redis.enabled .Values.externalRedis.enabled }}
  SPRING_CACHE_TYPE: "redis"
  SPRING_DATA_REDIS_HOST: {{ include "ehrbase.redisHost" . | quote }}
  SPRING_DATA_REDIS_PORT: {{ include "ehrbase.redisPort" . | quote }}
  MANAGEMENT_HEALTH_REDIS_ENABLED: "true"
  {{- end }}