{{- if and .Values.externalRedis.enabled (not .Values.externalRedis.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ehrbase.fullname" . }}-redis
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | default (randAlphaNum 30) | b64enc }}
{{- end }}