apiVersion: v1
kind: Service
metadata:
  name: {{ include "ehrbase.fullname" . }}
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ include "ehrbase.portName" . }}
      port: {{ .Values.service.port }}
      targetPort: {{ include "ehrbase.portName" . }}
      protocol: TCP
  selector:
    {{- include "ehrbase.selectorLabels" . | nindent 4 }}
