apiVersion: v1
kind: Service
metadata:
  name: {{ include "ehrbase.fullname" . }}
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ehrbase.selectorLabels" . | nindent 4 }}
